Project.toml
docs/make.jl
docs/src/SymbolicPermutation.md
docs/src/SymbolicWeightedPermutation.md
docs/src/histogram_estimation.md
src/symbolic/SymbolicPermutation.jl
src/symbolic/SymbolicWeightedPermutation.jl
src/symbolic/symbolic.jl
src/symbolic/utils.jl
test/runtests.jl

- Documentation improvements.
- New syntax (may still change): Symbolic estimator types have no arguments.

Symbolic weighted permutations

---

docs/src/Permutation.md

It got lost somewhere along the way when adding the `lt` field to the estimators.

Add permutation entropy example again

---

CHANGELOG.md
Project.toml
docs/src/index.md
src/Entropies.jl
src/tsallis/tsallis.jl
test/runtests.jl

Tsallis (non-logarithm) entropy.
Tsallis, C. (1988). Possible generalization of Boltzmann-Gibbs statistics. Journal of statistical physics, 52(1), 479-487.

Tsallis entropy

---

CHANGELOG.md
src/core.jl
src/symbolic/spatial_permutation.jl
src/symbolic/symbolic.jl
src/symbolic/symbolic_stencils.jl
test/runtests.jl
test/spatial_permutation_tests.jl

Closes #73
An alternative solution to #74 with really, really small source code and 10x better performance. It uses knowledge from Agents.jl.

Spatiotemporal Permutation Entropy

---

docs/src/complexity_measures.md
docs/src/entropies.md
docs/src/examples.md
docs/src/utils.md
src/complexity_measures/reverse_dispersion_entropy.jl
src/entropies/entropies.jl
src/entropies/normalized_entropy.jl
src/entropies/renyi.jl
src/entropies/shannon.jl
src/entropies/tsallis.jl
src/probabilities_estimators/dispersion/dispersion.jl
src/probabilities_estimators/permutation_ordinal/SymbolicAmplitudeAware.jl
src/probabilities_estimators/permutation_ordinal/SymbolicPermutation.jl
src/probabilities_estimators/permutation_ordinal/SymbolicWeightedPermutation.jl
src/probabilities_estimators/probabilities_estimators.jl
src/probabilities_estimators/utils.jl
src/symbolization/GaussianSymbolization.jl
test/dispersion.jl
test/runtests.jl

Hey, @Datseris. I've tried to address all your comments on #96  in this PR. 
- Added `alphabet_length` function that dispatches on estimators (throws error if alphabet length cannot be obtained)
- Standardised API for normalized Tsallis, Renyi and Shannon entropies.
- Added literature references justifying that normalization for symbolic entropy estimators are valid for all orders `q`.
- Made `distance_to_whitenoise` part of public API. 
- Some minor formatting and language fixes.
Some things to potentially discuss are:
- Instead of a single `entropy_normalized` function, I used `entropy_renyi_norm`,
`entropy_tsallis_norm` and `entropy_shannon_norm`. This mirrors the `entropy_renyi` and 
similar functions we already have. The alternative is to have `entropy_normalized(x, est = Renyi(); …

Addressing review comments

---

src/probabilities_estimators/permutation_ordinal/SymbolicPermutation.jl

Clarify what happens to embedding parameters when input is a dataset

---

docs/src/entropies.md
docs/src/examples.md
src/entropies/curado.jl
src/entropies/entropies.jl
src/entropy.jl
test/entropies/curado.jl
test/runtests.jl

This PR implements the Curado entropy (Curado & Nobre, 2004).
Contains:
- The `Curado` entropy type, which implements `entropy(e, probs::Probabilities)`, `entropy(e, x, est::ProbabilitiesEstimator` (through the interface), and `maximum`.
- A documentation entry.
- An example in the docs showcasing how the entropy behaves as a function of its parameter `b`, reproducing Figure 2 in Curado & Nobre (2004).
- Analytical tests from the original paper.
- A link in the `entropy` docstring to the method.
Curado, E. M., & Nobre, F. D. (2004). On the stability of analytic entropic forms. Physica A: Statistical Mechanics and its Applications, 335(1-2), 94-106.

Curado entropy

---

src/probabilities_estimators/permutation_ordinal/spatial_permutation.jl
test/estimators/permutation_spatial.jl

Hi there!
I added a few convenience methods for passing stencils to `SpatialSymbolicPermutation`, namely:
- for 2D and 3D, pass rectangular/ cuboid stencils just via their `extent` (an extension of the word length in 1d, just how many points should be considered in each direction, so that `word_length = prod(extent)`) and a lag in each direction as `SpatialSymbolicPermutation(extent, lag, x)`, such that
```julia
est = SpatialSymbolicPermutation((2, 2), (2, 2), x)
```
is equivalent to the original
```julia
stencil = CartesianIndex.([(0, 2), (2, 0), (2, 2)])
est = SpatialSymbolicPermutation(stencil, x)
```
- In general, pass n-dimensional `Array`s instead of a list of cartesian indices, where for example
```julia
stencil = [1 0 1;
0 0 0; 
1 0 1]
```
would correspond to the cartesian-index …

Added convenience methods for passing stencils to functions

---

src/probabilities_estimators/histograms/rectangular_binning.jl
test/estimators/visitation_frequency.jl

Fixes #128. Increasing bin edge widths by  `1*eps()` seems to be enough to avoid round-off issues in `encode_as_bin`. 
This seems to work when tested experimentally, but a more robust solution is perhaps desired. Any suggestions are welcome.

Slightly larger edge lengths ensures bins cover all points

---

CHANGELOG.md
docs/src/examples.md
src/entropies/direct_entropies/nearest_neighbors/KozachenkoLeonenko.jl
test/entropies/nearest_neighbors_direct.jl

In my original implementation for `KozchenkoLeonenko`, I included the number of nearest neighbors `k` as a variable the user could pick freely. However, the estimator from the Kozachenko-Leonenko original paper (as referenced in [Charzyńska et al](https://www.mdpi.com/1099-4300/18/1/13/htm)) does *not* allow picking `k` freely. It explicitly says that the formula is valid for the *nearest* (i.e. closest neighbor). 
In fact, because the formula for the estimator doesn't depend on `k` in any way, picking a `k != 1` would led to entropy estimates that are wildly off. 
I didn't catch this error before, because in all examples I tested and cross-referenced against true values (including the example in our documentation), I always picked `k = 1`.
This PR hard-codes `k = 1` and removes the …

KozachenkoLeonenko estimator should *not* have property `k`

---

CHANGELOG.md
docs/src/examples.md
src/entropies/direct_entropies/nearest_neighbors/KozachenkoLeonenko.jl
src/entropies/direct_entropies/nearest_neighbors/Kraskov.jl
test/entropies/nearest_neighbors_direct.jl

Correct conversion between logarithm bases for `Kraskov` and `KozachenkoLeonenko`

---

docs/src/entropies.md
docs/src/examples.md
src/entropies/direct_entropies/nearest_neighbors/Zhu.jl
src/entropies/direct_entropies/nearest_neighbors/nearest_neighbors.jl
test/entropies/nearest_neighbors_direct.jl

This PR implements the Zhu et al. estimator for Shannon entropy.
Included:
- Documentation entry + example
- Analytical tests using the entropy of the normal distribution
Zhu, J., Bellanger, J. J., Shu, H., & Le Bouquin Jeannès, R. (2015). Contribution to transfer entropy estimation via the k-nearest-neighbors approach. Entropy, 17(6), 4173-4201.

Indirect Zhu et al. kNN Shannon entropy estimator for univariate/multivariate data

---

Project.toml
src/encoding/ordinal_pattern.jl
src/encoding/utils.jl
src/probabilities_estimators/permutation_ordinal/SymbolicAmplitudeAware.jl
src/probabilities_estimators/permutation_ordinal/SymbolicPermutation.jl
src/probabilities_estimators/permutation_ordinal/SymbolicWeightedPermutation.jl
test/estimators/permutation.jl
test/estimators/permutation_amplitude_aware.jl
test/estimators/permutation_weighted.jl
test/utils/encoding.jl

Fixes #87.
Take-away:
- The outcome space for a permutation-based methods with parameter/dimension  `m` is
```julia
using Combinatorics
est = SymbolicPermutation(m = 3)
outcome_space = permutations(1:est.m) |> collect
```
- Each element in outcome space (`{π1, π2, ...., πfactorial(m)}`) is encoded to an integer `s(π) ∈ 0, 1, ..., factorial(m) - 1`.
- Decoding any of these integers with `decode(s, m)` yields the original permutation `π(s) ∈ outcome_space`.

WIP: Decode permutation, and `probabilities_and_outcomes` for ordinal permutation estimators

---

docs/src/examples.md

Many of the documentation examples won't build due to conflicting imports between `Entropies.entropy` and `Distributions.entropy`. This PR fixes that by explicitly importing only necessary types from Distributions.jl.

Fix conflicting import for `entropy`

---

src/encoding/ordinal_pattern.jl
src/encodings.jl
src/entropies/convenience_definitions.jl
src/entropy.jl
src/probabilities.jl
src/probabilities_estimators/counting/count_occurences.jl
src/probabilities_estimators/dispersion/dispersion.jl
src/probabilities_estimators/diversity/diversity.jl
src/probabilities_estimators/histograms/rectangular_binning.jl
src/probabilities_estimators/histograms/value_histogram.jl
src/probabilities_estimators/kernel/kernel_density.jl
src/probabilities_estimators/timescales/power_spectrum.jl
src/probabilities_estimators/timescales/wavelet_overlap.jl
test/convenience.jl
test/probabilities/estimators/count_occurrences.jl
test/probabilities/estimators/dispersion.jl
test/probabilities/estimators/diversity.jl
test/probabilities/estimators/timescales.jl
test/probabilities/estimators/value_histogram.jl
test/probabilities/interface.jl

Closes #185, closes #184
Implements the final version of the API which is:
- algorithm deciding arguments first, input data after.
- Also applies for `encode/decode`.
- Use funtions not functors
Also re-writes `FixedRectangularBinning` to have welldefined outcome space always.

Finish API

---

src/complexity/missing_patterns/missing_dispersion.jl
src/complexity/reverse_dispersion_entropy/reverse_dispersion_entropy.jl
src/encoding/gaussian_cdf.jl
src/encodings.jl
src/probabilities_estimators/dispersion/dispersion.jl
src/probabilities_estimators/kernel/kernel_density.jl
test/complexity/measures/missing_dispersion.jl
test/probabilities/estimators/dispersion.jl
test/probabilities/estimators/naive_kernel.jl

I have now adjusted the codebase so that `GaussianCDFEncoding` obeys the encoding API. This addresses another point in #190.
- Previously, `GaussianCDFEncoding` was only applicable to vector-valued input, meaning that we had to encode an entire timeseries in bulk. By adjusting the type from `GaussianCDFEncoding(; c::Int = 3)` to `GaussianCDFEncoding(; μ, σ, c::Int = 3)`, we now require the user to explicitly specify the mean and standard deviation of the desired normal CDF. Thus, `encode` and `decode` now both handle scalar-valued inputs (i.e. no need for entire timeseries, because `μ` and `σ` must be pre-computed). 
- In  the `Dispersion` struct, instead of explicitly constructing an encoding (i.e. `GaussianCDFEncoding)`, we just use `c::Int`, which dictates how many bins to divide the …

Adjust `GaussianCDFEncoding` and related stuff for new encoding API

---

docs/src/entropies.md
src/probabilities_estimators/permutation_ordinal/SymbolicPermutation.jl

Fixes #205.
Also improves the documentation for `SymbolicPermutation` and adds a literature reference for the multivariate permutation probabilities/entropy.

Simplify `SymbolicPermutation` source code

---

src/probabilities.jl
src/probabilities_estimators/dispersion/dispersion.jl
src/probabilities_estimators/spatial/spatial_dispersion/SpatialDispersion.jl
src/probabilities_estimators/spatial/spatial_permutation/SpatialSymbolicPermutation.jl
test/probabilities/estimators/spatial/spatial_dispersion.jl
test/probabilities/estimators/spatial/spatial_permutation.jl

Outcome space for `SpatialDispersion` and `SpatialSymbolicPermutation`

---

CHANGELOG.md
docs/src/entropies.md
docs/src/examples.md
src/entropies/estimators/nearest_neighbors/KozachenkoLeonenko.jl
src/entropies/estimators/nearest_neighbors/Kraskov.jl
src/entropies/estimators/nearest_neighbors/Zhu.jl
src/entropies/estimators/nearest_neighbors/ZhuSingh.jl
src/entropies/estimators/order_statistics/AlizadehArghami.jl
src/entropies/estimators/order_statistics/Correa.jl
src/entropies/estimators/order_statistics/Ebrahimi.jl
src/entropies/estimators/order_statistics/Vasicek.jl
src/entropy.jl
test/entropies/estimators/alizadeharghami.jl
test/entropies/estimators/correa.jl
test/entropies/estimators/ebrahimi.jl
test/entropies/estimators/kozachenkoleonenko.jl
test/entropies/estimators/kraskov.jl
test/entropies/estimators/vasicek.jl
test/entropies/estimators/zhu.jl
test/entropies/estimators/zhusingh.jl

Improvements:
- Use `Shannon(; base = 2)` as default for both discrete and differential entropy.
- *Document* that the default base is 2 and instruct the user to provide an `Entropy` instance if they want to specify the logarithm.
- Add small example for differential entropy in docstring for `entropy`.
- Conform to `Entropy` API: `base` is given to the `Entropy`, not the `EntropyEstimator`.
- All `EntropyEstimator` docstrings now explicitly explain what they compute (ref #209).
- Tests for all subtypes of `EntropyEstimator` re-done and standardized (ref #209).
Bug fix
- Fixed scaling issue for order statistic estimators (use natural log in formulas, only scale *after* the entropy has been computed). Thus, tests also can be much stricter, because they are not biased by erroneous scaling.

Differential entropy estimators: various fixes

---

CHANGELOG.md
Project.toml
src/probabilities.jl
test/entropies/estimators/alizadeharghami.jl
test/entropies/estimators/correa.jl
test/entropies/estimators/ebrahimi.jl
test/entropies/estimators/lord.jl
test/entropies/estimators/vasicek.jl

- Fixes some test failures 
- Adjusted docstring from `probabilities(x::Array_or_Dataset)` to `probabilities(x::Vector_or_Dataset)`. This method calls `fasthist!`, which actually only works for vector inputs. Fixing this is easy, so I'll open a separate issue for it.
- Fixes some tests that were randomly failing for `Lord` and order-statistics based differential entropy estimators, by allowing slightly higher lower deviations (we test on random data, and estimators are negatively biased)

Multidimensional probabilities

---

CHANGELOG.md
Project.toml
src/encoding_implementations/ordinal_pattern.jl
src/probabilities_estimators/symbolic_permutation.jl
test/runtests.jl
test/utils/encoding.jl
test/utils/utils.jl

A suggestion to fix #242.
- Encodings are part of the public API now, so re-introduce tests.
- Add an `isperm` keyword to `encode(::OrdinalPatternEncoding)`, so that the user can encode permutations directly too. If this option is unavailable, then the tests will fail, because the code calls `sortperm` on something which is already a permutation that would sort the input data. This is essentially `sortperm(sortperm(x))`, which destroys the one-to-one encoding-decoding. `encode(::OrdinalPatternEncoding, x)` behaves as before, but `encode(::OrdinalPatternEncoding, x; isperm = true)` skips the `sortperm` call.
- For `OrdinalPatternEncoding`, we test encoding/decoding against the example in table 1 in Berger et al. (2019).
- Updated the docstring for `OrdinalPatternEncoding`.

Ordinal patterns: better documentation and add tests again

---

Project.toml
src/probabilities.jl

Let me know if I should also bump the minor version.

Fix typo in ProbabilitiesEstimator docstring

---

CHANGELOG.md
Project.toml
src/ComplexityMeasures.jl
src/deprecations.jl
src/encoding_implementations/rectangular_binning.jl
src/probabilities_estimators/diversity.jl
src/probabilities_estimators/transfer_operator/transfer_operator.jl
src/probabilities_estimators/value_histogram.jl
test/probabilities/estimators/transfer_operator.jl
test/probabilities/estimators/value_histogram.jl

Our binning code was really bad when it came down to real world usage. When preparing the workshop, showing the ouputs of value histogram was alwas unintuitive. This thing we do with `n_eps` and `nextfloat` always leads to completely random and unintuitive numbers for the histogram edges. it also is very hard to get "the expected histogram" for different distribtions, hence computing the KL divergence. Furthermore, it is fundamentally inaccurate.
A much better approach is to give up trying to "hack up" some accuracy ourselves, and instead take advantage of Julia's base `range` system that operates using `TwicePrecision` to always keep range step sizes what the user expects without dealing with floating point precision. So that range `0:0.1:1` has exactly 0.1 step and exactly length of 11. …

Complete re-write of rectangular binnings to use ranges

---

Project.toml

I accidentally skipped v2.5.1, so the new package version won't register.

Decrement version. 

---

CHANGELOG.md
Project.toml
docs/src/entropies.md
src/entropies_estimators/nearest_neighbors/Gao.jl
src/entropies_estimators/nearest_neighbors/Goria.jl
src/entropies_estimators/nearest_neighbors/KozachenkoLeonenko.jl
src/entropies_estimators/nearest_neighbors/Kraskov.jl
src/entropies_estimators/nearest_neighbors/Lord.jl
src/entropies_estimators/nearest_neighbors/Zhu.jl
src/entropies_estimators/nearest_neighbors/ZhuSingh.jl
src/entropies_estimators/order_statistics/AlizadehArghami.jl
src/entropies_estimators/order_statistics/Correa.jl
src/entropies_estimators/order_statistics/Ebrahimi.jl
src/entropies_estimators/order_statistics/Vasicek.jl
src/entropy.jl
test/entropies/estimators/alizadeharghami.jl
test/entropies/estimators/correa.jl
test/entropies/estimators/ebrahimi.jl
test/entropies/estimators/estimators.jl
test/entropies/estimators/gao.jl
test/entropies/estimators/goria.jl
test/entropies/estimators/kozachenkoleonenko.jl
test/entropies/estimators/kraskov.jl
test/entropies/estimators/lord.jl
test/entropies/estimators/vasicek.jl
test/entropies/estimators/zhu.jl
test/entropies/estimators/zhusingh.jl

- Fixes #256 
Summary:
- Introduces a convenience method `convert_logunit` that converts between numbers computed with different logarithm bases. This method is exported as a convenience function, and is tested, to ensure the errors in #256 can never occur. However, it is *not* documented yet. We can decide later if it should be.
- Consistently use `convert_logunit` for all differential entropy estimator code and tests.
- Updates changelog.
- Increments package version.

Fix log units

---

Project.toml
src/encoding_implementations/rectangular_binning.jl
test/utils/bin_encoding.jl

While working on some fractal dimension estimators, I encountered this bug. If the maximum along a direction is exactly the end point of a range, our code does not extend the range for one more. This is wrong however as by our definition of the Fixed Binning,  the end point of the range is NOT included in the histogram, and hence the point itself is NOT included in the histogram, which is wrong.
This fixes it and adds a test.

fix binning when max point in range

---

src/complexity_measures/statistical_complexity.jl

The citation for Rosso2007 in statistical_complexity.jl [line 57](https://github.com/JuliaDynamics/ComplexityMeasures.jl/blob/339b510acae5dbd305fea7db8288760700cd1de4/src/complexity_measures/statistical_complexity.jl#L57) was formatted differently compared to the one in [line 129](https://github.com/JuliaDynamics/ComplexityMeasures.jl/blob/339b510acae5dbd305fea7db8288760700cd1de4/src/complexity_measures/statistical_complexity.jl#L129)

Streamline Citations in statistical_complexity.jl

---

docs/src/devdocs.md
src/core/counts.jl
src/core/probabilities.jl
src/encoding_implementations/rectangular_binning.jl
src/outcome_spaces/count_occurences.jl
src/outcome_spaces/dispersion.jl
src/outcome_spaces/diversity.jl
src/outcome_spaces/kernel_density.jl
src/outcome_spaces/power_spectrum.jl
src/outcome_spaces/spatial/spatial_dispersion/SpatialDispersion.jl
src/outcome_spaces/spatial/spatial_ordinal/SpatialOrdinalPatterns.jl
src/outcome_spaces/symbolic_permutation.jl
src/outcome_spaces/transfer_operator/transfer_operator.jl
src/outcome_spaces/value_histogram.jl
src/outcome_spaces/wavelet_overlap.jl
src/probabilities_estimators/Shrinkage.jl
src/probabilities_estimators/probabilities_estimators.jl
test/outcome_spaces/implementations/timescales.jl
test/outcome_spaces/implementations/value_histogram.jl

Fixes #297. 
The docs are [here](https://juliadynamics.github.io/ComplexityMeasures.jl/previews/PR305/).
Changes:
- `probabilities` and `probabilities_and_outcomes` generically dispatches to `counts` and `counts_and_outcomes`. 
- Counting-based `OutcomeSpace`s *must* implement `counts` and `counts_and_outcomes`. 
- Non-counting-based `OutcomeSpace`s *must* implement `probabilities` and `probabilities_and_outcomes` (since default dispatch don't work for them).
- Updated devdocs, such that there is one section for adding new `OutcomeSpace`s and one section for adding `ProbabilitiesEstimator`s.

Generic dispatch for `probabilities`

---

Project.toml
docs/Project.toml

`StatsBase` is needed for the doc build, but not otherwise. This PR moves the dependency on StatsBase from `Project.toml` to `docs/Project.toml`
Closes #307.

Remove `StatsBase` dependency

---

src/ComplexityMeasures.jl
src/core/counts.jl
src/core/print_counts_probs.jl
src/core/probabilities.jl

CC @Datseris,
This makes the printing of `Counts` and `Probabilities` much more minimalistic (ref discussion in #316).

Minimalistic printing for `Counts` and `Probabilities`

---

src/core/encodings.jl

We want to reduce development burden, which means don't mention outcome spaces here yet again, they are already discussed in the OutcomeSpace docstring.
Second, the return type should be explained at the first paragraph, not after the descriptin, as it has higher importance.

simplify docstring of codify

---

src/outcome_spaces/transfer_operator/transfer_operator.jl
test/outcome_spaces/implementations/transfer_operator.jl

Background in #337. Fixes #339.
- Added `rng` argument to `TransferOperator` and underlying functions. 
```julia
p1 = probabilities(TransferOperator(b; rng = MersenneTwister(1234)), D)
p2 = probabilities(TransferOperator(b; rng = MersenneTwister(1234)), D)
@test all(p1 .== p2) # true
rng = MersenneTwister(1234)
p1 = probabilities(TransferOperator(b; rng), D)
p2 = probabilities(TransferOperator(b; rng), D)
@test !all(p1 .== p2) # true
@test p1[1] ≈ p2[1] # true, since estimates are close
```

Reproducibility for `TransferOperator`

---

docs/src/devdocs.md
docs/src/examples.md
docs/src/probabilities.md
docs/src/tutorial.jl
src/core/counts.jl
src/core/information_functions.jl
src/core/outcome_spaces.jl
src/core/probabilities.jl
src/deprecations.jl
src/probabilities_estimators/AddConstant.jl
src/probabilities_estimators/BayesianRegularization.jl
src/probabilities_estimators/RelativeAmount.jl
src/probabilities_estimators/Shrinkage.jl
test/convenience.jl
test/deprecations.jl

Some necessary changes to get #347 to pass CI and adhere to API.
- `probabilities_and_outcomes` and `allprobabilities_and_outcomes` are consistently the methods implemented, and `probabilities`/`allprobabilities` are just calls to those functions. The exception is if implementing the latter methods is faster.
- Fixed missing methods and exports (why were they removed to begin with, @Datseris? I'm thinking specifically of the `allcounts` etc methods that were generated previously)
- `entropy(::Probabilities)`, which was used in the doc tutorial, is not a valid syntax. I am happy with that, since I like to specify which entropy one wants to compute. However, we can also dispatch automatically to `entropy(Shannon(), p)`. Not sure what is the best. Here I just modified the examples in the …

Refactoring and fixes for the `tutorial` branch

---

src/outcome_spaces/ordinal_patterns.jl
test/outcome_spaces/implementations/permutation.jl

Error message clarification of `codify` discussed  here #358

Add functionality clarifying method to codify

---

src/outcome_spaces/ordinal_patterns.jl

Addresses https://github.com/JuliaDynamics/ComplexityMeasures.jl/pull/359#issuecomment-1880996987.

Move input check for `codify` with 1-dimensional state space sets and ordinal outcome spaces

---

Project.toml
src/deprecations.jl

See the syntax mentioned in https://github.com/JuliaDynamics/ComplexityMeasures.jl/issues/366

Add missing method with q first for deprecated `genentropy`

---

Project.toml
src/core/counts.jl
src/core/probabilities.jl
test/counts/core.jl
test/deprecations.jl
test/probabilities/probabilities.jl

Closes #369.
Also fixes broken tests on `main` introduced by https://github.com/JuliaDynamics/ComplexityMeasures.jl/commit/1ebda7bf05aa2c7c1f4221a5ef59f38f500143b9, where tests where not updated in accordance with the new deprecation message.

Fix method ambiguity and add tests for Base array extensions

---

src/deprecations.jl
src/outcome_spaces/ordinal_patterns.jl
test/deprecations.jl

Fixes #372. 
I also parameterized the `τ` field of the structs explicitly. These were previously hard-coded as `Int`, but there's no reason why we should be so strict.

Deprecate ordinal outcome space constructors

---

CHANGELOG.md
Project.toml
src/ComplexityMeasures.jl
src/complexity_measures/statistical_complexity.jl
src/core/pretty_printing.jl
src/encoding_implementations/combination_encoding.jl
src/encoding_implementations/gaussian_cdf.jl
src/encoding_implementations/ordinal_pattern.jl
src/encoding_implementations/relative_first_difference_encoding.jl
src/encoding_implementations/relative_mean_encoding.jl
src/outcome_spaces/ordinal_patterns.jl
test/complexity/measures/statistical_complexity.jl
test/encodings/encodings/combination_encoding.jl
test/encodings/encodings/gaussian_cdf_encoding.jl
test/encodings/encodings/ordinal_pattern_encoding.jl
test/pretty_printing.jl
test/runtests.jl

Fixes #286.
Introduces:
- `core/pretty_printing.jl`. Contains generic pretty-printing code for relevant types in our package. Defines
- The vector `our_abstract_types`, which lists the types for which we want to pretty-print.
- Functions that can be overridden if special printing for individual types are needed. For example:
- `hidefields` can be overridden to not display certain internal fields. Used e.g. for `RelativeMeanEncoding` to hide the `binencoder` field.
- `special_typeparameter_info` can be overridden to display certain extra type information. By default, all type annotations are stripped away while pretty-printing. However, for `OrdinalPatterns` we want it to be printed as `OrdinalPatterns{3}(...)` and not `OrdinalPatterns(...)`. Overriding this method takes care of that.
- …

Nicer default printing

---

Project.toml
src/core/counts.jl
src/core/probabilities.jl

Fixes the remainder of #370.
- There was no mention of `Counts` at all in the `Probabilities` doctoring, so the `probs_or_counts` argument in the docstring wasn't really making much sense. Therefore, I split the constructor signature up into two lines, and explicitly reference `Counts`.
- Clarified that when inputting `Counts` without specifying `outcomes`, then the outcomes are inherited from `Counts`.
- Slight rewording and a few extra words to make it explicit what "probabilities correspond to outcomes that describe axes" mean.  
- Added a few short examples of constructing a `Probabilities` (show, don't tell). This point can be omitted, but I find it useful.

Better docstrings for probs and counts

---

CHANGELOG.md
Project.toml
docs/src/probabilities.md
src/complexity_measures/missing_dispersion.jl
src/core/probabilities.jl
src/deprecations.jl
test/complexity/missing_outcomes.jl

This PR simplifies the docstring and source codes of missing dispersion patterns and missing outcomes.
It also sets the `all` keyword of `missing_outomces` to `false`. Why would this be `true`? It is computationally more expensive and leads to the same outcome. Furthermore, I would even argue, why would `all` _ever_ be used? This keyword appears useless at first glance. Perhaps we should deprecate it?

Simplify MDP and missing outcomes

---

CHANGELOG.md
Project.toml
docs/refs.bib
docs/src/information_measures.md
src/information_measure_definitions/fluctuation_complexity.jl
src/information_measure_definitions/information_measure_definitions.jl
test/infomeasures/infomeasure_types/fluctuation_complexity.jl
test/infomeasures/infomeasures.jl

The fluctuation complexity characterizes the deviations of the information content of individual states from some summary statistic (information measure) computed for the same distribution. I've here generalized the original measure, which uses Shannon entropy, to be compatible with any `InformationMeasure`.
- Updated changelog and version.
- A bibtex entry for the original reference.
- The `FluctuationComplexity` type, which can be used with `information` in combination with any estimation method, just like the other entropies & friends.
- A documentation entry.
- Analytical tests for the case of using `Shannon` entropy as the summary statistic.
- Note: There's no `information_maximum` method for now, because I couldn't see any of generally computing the maximum value without some …

Implement fluctuation complexity

---

Project.toml
src/encoding_implementations/unique_elements_encoding.jl
src/outcome_spaces/unique_elements.jl
test/encodings/encodings/unique_elements_encoding.jl
test/outcome_spaces/implementations/unique_elements.jl

While working on the latest version of CausalityTools.jl, I encountered a weird bug that turned out to have its root in ComplexityMeasures.jl: `codify`ing certain types of state space sets with `UniqueElements` didn't work. This happened because the `unique(x)`call errored. In turn, this happens because `unique` isn't implemented for `AbstractStateSpaceSet`s. 
I fix this here by using `vec` to get the data (which works both for regular vectors and for state space sets). This is now tested explicitly. 
I also ensure that we get the correct element types for the dicts, and use an outer constructor because there's nothing special happening in it requiring it to be an inner constructor.

Bug fix in `UniqueElementsEncoding`

---

CHANGELOG.md
Project.toml
src/core/probabilities.jl
test/probabilities/probabilities.jl

https://github.com/JuliaDynamics/ComplexityMeasures.jl/pull/422 changed the following
```Julia
function Probabilities(x::AbstractArray{T, N},
outcomes::Tuple{Vararg{V, N} where V},
dimlabels::NTuple{N, S};
normed::Bool = false)
```
to 
```Julia
function Probabilities(x::AbstractArray{T, N},
outcomes::Tuple{Vararg{V, N}} where V,
dimlabels::NTuple{N, S};
normed::Bool = false)
```
The change was `outcomes::Tuple{Vararg{V, N} where V}` => `outcomes::Tuple{Vararg{V, N}} where V`. 
The first part of the PR does address the deprecation warning the PR was supposed to solve (https://github.com/JuliaDynamics/ComplexityMeasures.jl/issues/419). However, the second change (the above), is not related to the deprecation warning. More seriously, this fundamentally changes the meaning of the type …

Fix erroneous change of constructor signature.

---

Project.toml
src/core/probabilities.jl
src/outcome_spaces/cosine_similarity_binning.jl
src/probabilities_estimators/AddConstant.jl

In #427, I fixed the error disallowing different-type outcome containers for `Probabilities`. However, that introduced the deprecation warning again. This fixes the resulting deprecations warning.

Fix deprecation
