- docs/src/VisitationFrequency.md
Rename some functions, simplify docs
> Documentation fixes

- docs/make.jl
- docs/src/SymbolicPermutation.md
- docs/src/SymbolicWeightedPermutation.md
- docs/src/probabilities.md
- src/binning_based/rectangular/VisitationFrequency.jl
- src/generalized_entropy.jl
- src/histogram_estimation.jl
- src/symbolic/SymbolicPermutation.jl
- src/symbolic/SymbolicWeightedPermutation.jl
- src/symbolic/utils.jl
- test/runtests.jl
> New syntax

- Project.toml
- docs/make.jl
- docs/src/CountOccurrences.md
- docs/src/SymbolicAmplitudeAwarePermutation.md
- docs/src/SymbolicPermutation.md
- docs/src/VisitationFrequency.md
- docs/src/generalized_entropy.md
- docs/src/probabilities.md
- src/Entropies.jl
- src/binning_based/rectangular/VisitationFrequency.jl
- src/binning_based/rectangular/binning_schemes.jl
- src/binning_based/rectangular/histogram_estimation.jl
- src/counting_based/CountOccurrences.jl
- src/generalized_entropy.jl
- src/histogram_estimation.jl
- src/symbolic/SymbolicAmplitudeAware.jl
- src/symbolic/SymbolicPermutation.jl
- src/symbolic/SymbolicWeightedPermutation.jl
- src/symbolic/symbolic.jl
- test/runtests.jl
Plus documentation improvements
> Amplitude-aware permutations and occurrence counting

- src/entropies/renyi.jl
- test/entropies/renyi.jl
I feel like our test suite is super weak. Many clauses are not tested... We should take the coverage results seriously at some point and write tests for whatever isn't tested. Anyways, this is fixed now!
> fix renyi for q = 0

- .github/PULL_REQUEST_TEMPLATE/new_entropy_template.md
- .github/PULL_REQUEST_TEMPLATE/new_probabilities_estimator.md
> PR template for `ProbabilitiesEstimator`s

- docs/src/examples.md
This PR removes the reverse dispersion (complexity) example and fixes the regular dispersion example.
> Remove reverse dispersion example

- src/probabilities.jl
- src/probabilities_estimators/histograms/rectangular_binning.jl
- src/probabilities_estimators/transfer_operator/transfer_operator.jl
- test/estimators/transfer_operator.jl
> Fix `TransferOperator`

- docs/src/entropies.md
- docs/src/examples.md
- docs/src/index.md
- docs/src/probabilities.md
- src/entropies/estimators/nearest_neighbors/KozachenkoLeonenko.jl
- src/entropies/estimators/nearest_neighbors/Kraskov.jl
- src/entropies/estimators/nearest_neighbors/Zhu.jl
- src/entropies/estimators/nearest_neighbors/ZhuSingh.jl
- src/entropies/estimators/order_statistics/AlizadehArghami.jl
- src/entropies/estimators/order_statistics/Correa.jl
- src/entropies/estimators/order_statistics/Ebrahimi.jl
- src/entropies/estimators/order_statistics/Vasicek.jl
- src/entropy.jl
> Clarify dicsrete vs. differential estimators

- src/probabilities_estimators/transfer_operator/transfer_operator.jl
- test/probabilities/estimators/transfer_operator.jl
> Use new binning encodings for transfer operator

- src/encoding/ordinal_pattern.jl
> Ensure encodings are strictly positive integers

- test/probabilities/estimators/spatial/spatial_permutation.jl
Add remaining analytical API method test for `probabilities_and_outcomes`
> Add missing test for `SpatialSymbolicPermutation`

- test/entropies/estimators/alizadeharghami.jl
- test/entropies/estimators/correa.jl
- test/entropies/estimators/ebrahimi.jl
- test/entropies/estimators/kozachenkoleonenko.jl
- test/entropies/estimators/kraskov.jl
- test/entropies/estimators/vasicek.jl
- test/entropies/estimators/zhu.jl
- test/entropies/estimators/zhusingh.jl
> Allow some wiggle-room for analytical differential entropy tests

- Project.toml
- docs/src/complexity.md
- docs/src/index.md
- src/complexity.jl
- src/complexity_measures/approximate_entropy.jl
- src/complexity_measures/missing_dispersion.jl
- src/complexity_measures/reverse_dispersion_entropy.jl
- src/complexity_measures/sample_entropy.jl
- src/deprecations.jl
- src/multiscale.jl
- src/multiscale/multiscale.jl
- src/probabilities_estimators/diversity.jl
- src/probabilities_estimators/spatial/spatial_dispersion/SpatialDispersion.jl
- src/probabilities_estimators/symbolic_permutation.jl
- test/entropies/interface.jl
- test/probabilities/estimators/permutation.jl
- test/probabilities/estimators/spatial/spatial_dispersion.jl
@kahaaga I need some help here: the test for the non-encoded spatial dispersion patterns fails, but I am not sure why. I fixed a problem in the code with the normalization in the previous PR. But I am not sure what I did wrong to make this fail.
> Fix some bugs

- Project.toml
- docs/src/examples.md
> Differential entropy documentation example fix

- docs/src/index.md
- src/ComplexityMeasures.jl
- src/deprecations.jl
- src/encoding_implementations/rectangular_binning.jl
- src/entropy.jl
- src/probabilities.jl
- src/probabilities_estimators/symbolic_permutation.jl
- src/probabilities_estimators/transfer_operator/transfer_operator.jl
And add according information that `SSSet` means `StateSPaceSet`.
> Rename `Dataset` to `SSSet` in docstrings

- src/differential_info_estimators/nearest_neighbors/Gao.jl
- src/differential_info_estimators/nearest_neighbors/Goria.jl
- src/differential_info_estimators/nearest_neighbors/KozachenkoLeonenko.jl
- src/differential_info_estimators/nearest_neighbors/Kraskov.jl
- src/differential_info_estimators/nearest_neighbors/Lord.jl
- src/differential_info_estimators/nearest_neighbors/Zhu.jl
- src/differential_info_estimators/nearest_neighbors/ZhuSingh.jl
- src/differential_info_estimators/order_statistics/AlizadehArghami.jl
- src/differential_info_estimators/order_statistics/Correa.jl
- src/differential_info_estimators/order_statistics/Ebrahimi.jl
- src/differential_info_estimators/order_statistics/Vasicek.jl
- test/infomeasures/estimators/alizadeharghami.jl
- test/infomeasures/estimators/correa.jl
- test/infomeasures/estimators/ebrahimi.jl
- test/infomeasures/estimators/gao.jl
- test/infomeasures/estimators/goria.jl
- test/infomeasures/estimators/kozachenkoleonenko.jl
- test/infomeasures/estimators/kraskov.jl
- test/infomeasures/estimators/lord.jl
- test/infomeasures/estimators/vasicek.jl
- test/infomeasures/estimators/zhu.jl
- test/infomeasures/estimators/zhusingh.jl
> Logarithm for differential entropy estimators from the *definition*, not the estimator itself

- test/infomeasures/infomeasure_types/curado.jl
Added test cases in curado.jl
for issue #85
> Added test cases in curado.jl

- src/encoding_implementations/rectangular_binning.jl
updated to AbstractFloat
Fixing issue #150
> Binning restrictions to Float64

- test/outcome_spaces/implementations/spatial/spatial_ordinal_patterns.jl
increasing coverage for:
1) SpatialOrdinaryPatterns.jl  added testcases to test the show method for SpatialOrdinalPatterns
For increasing code coverage 
issue #85 fixing
> increasing coverage for :

- docs/src/probabilities.md
> add new `codify` function to docs

- docs/src/probabilities.md
- src/core/outcome_spaces.jl
because it is used often in the literature
> Highlight the name "symbolization" more

- docs/src/tutorial.jl
- src/core/counts.jl
- src/core/print_counts_probs.jl
- test/counts/core.jl
- test/probabilities/probabilities.jl
> Pretty printing

- CHANGELOG.md
- README.md
- docs/src/devdocs.md
- docs/src/examples.md
- docs/src/probabilities.md
- docs/src/tutorial.jl
- src/core/counts.jl
- src/core/information_functions.jl
- src/core/outcome_spaces.jl
- src/core/probabilities.jl
- src/deprecations.jl
- src/outcome_spaces/value_binning.jl
- src/probabilities_estimators/AddConstant.jl
- src/probabilities_estimators/BayesianRegularization.jl
- src/probabilities_estimators/RelativeAmount.jl
- src/probabilities_estimators/Shrinkage.jl
- test/convenience.jl
- test/deprecations.jl
This needs the pretty printing to be finished. There is also the matter of resolving this comment: https://github.com/JuliaDynamics/ComplexityMeasures.jl/pull/341#issuecomment-1862365859
> Finish tutorial and API reference for v3

- src/encoding_implementations/combination_encoding.jl
- test/encodings/encodings/combination_encoding.jl
> Ensured that empty CombinationEncoding isn't possible

- Project.toml
- src/core/information_measures.jl
- src/discrete_info_estimators/chao_shen.jl
- src/discrete_info_estimators/horvitz_thompson.jl
- src/discrete_info_estimators/jackknife.jl
- src/discrete_info_estimators/miller_madow.jl
- src/discrete_info_estimators/plugin.jl
- src/discrete_info_estimators/schurmann.jl
- src/discrete_info_estimators/schurmann_generalized.jl
makes it easier to calculate total measures
> add more subtyping information to discrete info esti

- Project.toml
- README.md
Now that the paper is online, we can make these statements in the readme to promote the software more.
> promote package based on paper proof

- Project.toml
- src/core/print_counts_probs.jl
- src/core/probabilities.jl
> Fix deprecation warnings on Vararg
